version: "3.9"

volumes:
  cloud-boostclicks-db-volume:
    name: cloud-boostclicks-db-volume

networks:
  cloud-boostclicks-network:
    name: cloud-boostclicks-network

services:
  cloud-boostclicks:
    container_name: cloud-boostclicks
    image: cloud-boostclicks
    build:
      context: .
      args:
        VITE_TELEGRAM_LOGIN_BOT_USERNAME: ${VITE_TELEGRAM_LOGIN_BOT_USERNAME}
    env_file:
      - .env
    ports:
      - ${PORT}:8000
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - cloud-boostclicks-network

  db:
    container_name: cloud-boostclicks-db
    image: postgres:15.0-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: pg_isready --username=${DATABASE_USER} --dbname=${DATABASE_NAME}
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - cloud-boostclicks-db-volume:/var/lib/postgresql/data
    networks:
      - cloud-boostclicks-network
